language: python
os: linux
dist: xenial

python:
  - "3.6"

git:
  submodules: false

jobs:
  include:
    - name: "lint"

      install: 
        - pip install -r requirements.txt
        - pip install tox-travis
      
      script:
        - flake8
        - black . --check --diff
      
    - name: "tests"

      before_install:
        - chmod +x ./app/lib/a.out
       
      install:
        - pip install -r requirements.txt
        - pip install tox-travis
      
      script:
        - tox
        - coverage run -m pytest
      
      after_success:
        - coveralls
    
    - name: "docker build"
      
      services:
        - docker
      
      script:
        - docker build -t spell_check .
      