language: python
os: linux
dist: xenial

python:
  - "3.6"

git:
  submodules: false

jobs:
  include:
    - name: "lint"

      install: 
        - pip install -r requirements.txt
        - pip install tox-travis
      
      script:
        - flake8
        - black . --check --diff
      
    - name: "tests"

      # before_install:
      #   - git submodule update --init --recursive
      #   - pip install cpp-coveralls gcovr
      #   - sudo apt-get update -y && sudo apt-get -y install build-essential check pkg-config
      #   - mkdir app/lib/spell_check/bin
      #   - mkdir app/lib/spell_check/build
      #   - cd app/lib/spell_check/build
      #   - cmake ..
      #   - make
      #   - cd $TRAVIS_BUILD_DIR
       
      install:
        - pip install -r requirements.txt
        - pip install tox-travis
      
      script:
        - tox
        - coverage run -m pytest
      
      after_success:
        - coveralls