language: python
os: linux
dist: xenial
python:
  - "3.6"


install: 
  - pip install -r requirements.txt
  - pip install tox-travis
  - pip install -e .


script: 
  - tox
  - coverage run -m pytest

on_success:
  - coveralls