language: python
os: linux
dist: xenial

python:
  - "3.6"

git:
  submodules: false

jobs:
  include:
    - name: "lint"

      install: 
        - pip install -r requirements.txt
        - pip install tox-travis
        - pip install -e .
      
      script:
        - flake8
        - black . --check --diff
      
    - name: "tests"

      before_install:
        - git submodule update --init --recursive
        - pip install --user cpp-coveralls gcovr
        - sudo apt-get update -y && sudo apt-get -y install build-essential check pkg-config
        - mkdir spellr/lib/spell_check/bin
        - mkdir spellr/lib/spell_check/build
        - cd spellr/lib/spell_check/build
        - cmake ..
        - make
       
      install:
        - pip install -r requirements.txt
        - pip install tox-travis
        - pip install -e .
      
      script:
        - tox
        - coverage run -m pytest
      
      after_success:
        - coveralls