language: python
os: linux
dist: xenial
python:
  - "3.6"

jobs:
  include:
    - name: "lint"

      install: 
        - pip install -r requirements.txt
        - pip install tox-travis
        - pip install -e .
      
      script:
        - flake8
        - black . --check --diff
      
    - name: "tests"
       
      install:
        - pip install -r requirements.txt
        - pip install tox-travis
        - pip install -e .
      
      script:
        - tox
        - coverage run -m pytest
      
      after_success:
        - coveralls