version: "3"
services: 
    app:
        build: .
        ports:
            - 8080:5000
        environment: 
            - FLASK_APP=app.py
            - FLASK_ENV=production
            - DATABASE_URL=sqlite:////tmp/spellr.sqlite
            - SECRET_KEY=not-so-secret-yet
            - ADMIN_USER=admin
            - ADMIN_PASS=Administrator@1
            - ADMIN_TF=12345678901
            - TEST_USER=test_user
            - TEST_PASS=password
            - TEST_TF=11231231234