apiVersion: v1
kind: PersistentVolume
metadata:
    name: sqlite-pv-volume
    labels:
        name: local
spec:
    storageClassName: manual
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: "/tmp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: sqlite-pv-claim
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi